import { CreateAssistantDTO } from "@vapi-ai/web/dist/api";
import { z } from "zod";

export const mappings = {
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vuejs",
  vuejs: "vuejs",
  vue: "vuejs",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "node.js": "nodejs",
  nodejs: "nodejs",
  node: "nodejs",
  mongodb: "mongodb",
  mongo: "mongodb",
  mongoose: "mongoose",
  mysql: "mysql",
  postgresql: "postgresql",
  sqlite: "sqlite",
  firebase: "firebase",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  digitalocean: "digitalocean",
  heroku: "heroku",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  html5: "html5",
  html: "html5",
  css3: "css3",
  css: "css3",
  sass: "sass",
  scss: "sass",
  less: "less",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  jquery: "jquery",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "ember.js": "ember",
  emberjs: "ember",
  ember: "ember",
  "backbone.js": "backbone",
  backbonejs: "backbone",
  backbone: "backbone",
  nestjs: "nestjs",
  graphql: "graphql",
  "graph ql": "graphql",
  apollo: "apollo",
  webpack: "webpack",
  babel: "babel",
  "rollup.js": "rollup",
  rollupjs: "rollup",
  rollup: "rollup",
  "parcel.js": "parcel",
  parceljs: "parcel",
  npm: "npm",
  yarn: "yarn",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  figma: "figma",
  prisma: "prisma",
  redux: "redux",
  flux: "flux",
  redis: "redis",
  selenium: "selenium",
  cypress: "cypress",
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  karma: "karma",
  vuex: "vuex",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  nuxt: "nuxt",
  strapi: "strapi",
  wordpress: "wordpress",
  contentful: "contentful",
  netlify: "netlify",
  vercel: "vercel",
  "aws amplify": "amplify",
};

export const interviewer: CreateAssistantDTO = {
  name: "Interviewer",
  firstMessage:
    "Hello! Thank you for taking the time to speak with me today. I'm excited to learn more about you and your experience.",
  transcriber: {
    provider: "deepgram",
    model: "nova-2",
    language: "en",
  },
  voice: {
    provider: "11labs",
    voiceId: "sarah",
    stability: 0.4,
    similarityBoost: 0.8,
    speed: 0.9,
    style: 0.5,
    useSpeakerBoost: true,
  },
  model: {
    provider: "openai",
    model: "gpt-4",
    messages: [
      {
        role: "system",
        content: `You are a professional job interviewer conducting a real-time voice interview with a candidate. Your goal is to assess their qualifications, motivation, and fit for the role.

Interview Guidelines:
Follow the structured question flow:
{{questions}}

Engage naturally & react appropriately:
Listen actively to responses and acknowledge them before moving forward.
Ask brief follow-up questions if a response is vague or requires more detail.
Keep the conversation flowing smoothly while maintaining control.
Be professional, yet warm and welcoming:

Use official yet friendly language.
Keep responses concise and to the point (like in a real voice interview).
Avoid robotic phrasing—sound natural and conversational.
Answer the candidate’s questions professionally:

If asked about the role, company, or expectations, provide a clear and relevant answer.
If unsure, redirect the candidate to HR for more details.

Conclude the interview properly:
Thank the candidate for their time.
Inform them that the company will reach out soon with feedback.
End the conversation on a polite and positive note.


- Be sure to be professional and polite.
- Keep all your responses short and simple. Use official language, but be kind and welcoming.
- This is a voice conversation, so keep your responses short, like in a real conversation. Don't ramble for too long.`,
      },
    ],
  },
  clientMessages: [], // <- required
  serverMessages: [], // <- required
};

export const feedbackSchema = z.object({
  totalScore: z.number(),
  categoryScores: z.tuple([
    z.object({
      name: z.literal("Communication Skills"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Technical Knowledge"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Problem Solving"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Cultural Fit"),
      score: z.number(),
      comment: z.string(),
    }),
    z.object({
      name: z.literal("Confidence and Clarity"),
      score: z.number(),
      comment: z.string(),
    }),
  ]),
  strengths: z.array(z.string()),
  areasForImprovement: z.array(z.string()),
  finalAssessment: z.string(),
});

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hostinger.png",
  "/pinterest.png",
  "/quora.png",
  "/reddit.png",
  "/skype.png",
  "/spotify.png",
  "/telegram.png",
  "/tiktok.png",
  "/yahoo.png",
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: [
      "What is React and how does it work?",
      "Explain the virtual DOM.",
      "How do you manage state in React?",
    ],
    finalized: true,
    createdAt: "2024-04-01T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Full Stack Developer",
    type: "Mixed",
    techstack: ["Node.js", "Express", "MongoDB", "React"],
    level: "Senior",
    questions: [
      "What is Node.js and how is it used in full stack development?",
      "How does MongoDB differ from SQL databases?",
      "Explain the request-response cycle in Express.",
    ],
    finalized: true,
    createdAt: "2024-04-02T10:00:00Z",
  },
  {
    id: "3",
    userId: "user1",
    role: "Backend Developer",
    type: "Technical",
    techstack: ["Node.js", "Express", "MySQL"],
    level: "Mid",
    questions: [
      "Explain RESTful APIs.",
      "How do you handle database migrations in MySQL?",
      "What are middlewares in Express?",
    ],
    finalized: true,
    createdAt: "2024-04-03T10:00:00Z",
  },
  {
    id: "4",
    userId: "user2",
    role: "DevOps Engineer",
    type: "Technical",
    techstack: ["Docker", "Kubernetes", "AWS"],
    level: "Senior",
    questions: [
      "How do you scale a containerized application?",
      "What’s the difference between Docker and Kubernetes?",
      "How do you set up CI/CD pipelines in AWS?",
    ],
    finalized: true,
    createdAt: "2024-04-04T10:00:00Z",
  },
  {
    id: "5",
    userId: "user2",
    role: "Mobile App Developer",
    type: "Technical",
    techstack: ["React Native", "Firebase"],
    level: "Junior",
    questions: [
      "How do you handle state in React Native?",
      "How do you connect a React Native app with Firebase?",
      "Explain performance optimizations in mobile apps.",
    ],
    finalized: true,
    createdAt: "2024-04-05T10:00:00Z",
  },
  {
    id: "6",
    userId: "user3",
    role: "UI/UX Designer",
    type: "Behavioral",
    techstack: ["Figma", "Photoshop"],
    level: "Mid",
    questions: [
      "How do you design user-friendly interfaces?",
      "Describe your design process from concept to prototype.",
      "How do you incorporate user feedback into your designs?",
    ],
    finalized: true,
    createdAt: "2024-04-06T10:00:00Z",
  },
  {
    id: "7",
    userId: "user3",
    role: "Data Scientist",
    type: "Technical",
    techstack: ["Python", "TensorFlow", "Pandas"],
    level: "Senior",
    questions: [
      "What is overfitting in machine learning?",
      "How do you clean and preprocess large datasets?",
      "Explain the difference between supervised and unsupervised learning.",
    ],
    finalized: true,
    createdAt: "2024-04-07T10:00:00Z",
  },
  {
    id: "8",
    userId: "user4",
    role: "ML Engineer",
    type: "Mixed",
    techstack: ["PyTorch", "Scikit-learn", "Docker"],
    level: "Mid",
    questions: [
      "Explain the difference between classification and regression.",
      "How do you deploy ML models using Docker?",
      "What is model drift and how do you handle it?",
    ],
    finalized: true,
    createdAt: "2024-04-08T10:00:00Z",
  },
  {
    id: "9",
    userId: "user4",
    role: "Cloud Engineer",
    type: "Technical",
    techstack: ["AWS", "Azure", "Terraform"],
    level: "Senior",
    questions: [
      "What is Infrastructure as Code (IaC)?",
      "How does AWS differ from Azure in terms of deployment?",
      "What are common security practices for cloud environments?",
    ],
    finalized: true,
    createdAt: "2024-04-09T10:00:00Z",
  },
  {
    id: "10",
    userId: "user5",
    role: "Security Analyst",
    type: "Technical",
    techstack: ["Kali Linux", "Wireshark", "Snort"],
    level: "Junior",
    questions: [
      "What is a firewall and how does it work?",
      "How do you perform a vulnerability scan?",
      "Explain the difference between IDS and IPS.",
    ],
    finalized: true,
    createdAt: "2024-04-10T10:00:00Z",
  },
  {
    id: "11",
    userId: "user5",
    role: "QA Engineer",
    type: "Technical",
    techstack: ["Selenium", "JUnit", "Postman"],
    level: "Mid",
    questions: [
      "What is regression testing?",
      "How do you automate browser testing with Selenium?",
      "How do you test APIs using Postman?",
    ],
    finalized: true,
    createdAt: "2024-04-11T10:00:00Z",
  },
  {
    id: "12",
    userId: "user6",
    role: "AI Researcher",
    type: "Technical",
    techstack: ["PyTorch", "HuggingFace", "NLP"],
    level: "Senior",
    questions: [
      "Explain the transformer architecture.",
      "How do you fine-tune a pre-trained language model?",
      "What are challenges in training large NLP models?",
    ],
    finalized: true,
    createdAt: "2024-04-12T10:00:00Z",
  },
  {
    id: "13",
    userId: "user6",
    role: "Game Developer",
    type: "Technical",
    techstack: ["Unity", "C#", "Blender"],
    level: "Mid",
    questions: [
      "What is a game loop?",
      "How do you handle physics in Unity?",
      "Explain the process of asset integration using Blender.",
    ],
    finalized: true,
    createdAt: "2024-04-13T10:00:00Z",
  },
  {
    id: "14",
    userId: "user7",
    role: "Systems Engineer",
    type: "Mixed",
    techstack: ["Linux", "Bash", "Ansible"],
    level: "Senior",
    questions: [
      "How do you automate configuration with Ansible?",
      "Describe memory management in Linux.",
      "How do you monitor system performance?",
    ],
    finalized: true,
    createdAt: "2024-04-14T10:00:00Z",
  },
  {
    id: "15",
    userId: "user8",
    role: "Technical Writer",
    type: "Behavioral",
    techstack: ["Markdown", "Git", "Notion"],
    level: "Junior",
    questions: [
      "How do you explain technical topics to non-technical users?",
      "How do you organize your documentation process?",
      "What tools do you use for version control?",
    ],
    finalized: true,
    createdAt: "2024-04-15T10:00:00Z",
  },
  {
    id: "16",
    userId: "user8",
    role: "Blockchain Developer",
    type: "Technical",
    techstack: ["Solidity", "Ethereum", "Hardhat"],
    level: "Mid",
    questions: [
      "What is a smart contract?",
      "How do you write and deploy contracts using Solidity?",
      "What is the difference between public and private blockchains?",
    ],
    finalized: true,
    createdAt: "2024-04-16T10:00:00Z",
  },
  {
    id: "17",
    userId: "user9",
    role: "Product Manager",
    type: "Behavioral",
    techstack: ["Jira", "Figma", "Agile"],
    level: "Senior",
    questions: [
      "How do you prioritize features in a product roadmap?",
      "Describe a challenging project and how you handled it.",
      "How do you gather user feedback effectively?",
    ],
    finalized: true,
    createdAt: "2024-04-17T10:00:00Z",
  },
  {
    id: "18",
    userId: "user9",
    role: "Software Architect",
    type: "Technical",
    techstack: ["Microservices", "Kafka", "Redis"],
    level: "Senior",
    questions: [
      "What are the key principles of software architecture?",
      "How do you design for scalability?",
      "What are common challenges in microservice communication?",
    ],
    finalized: true,
    createdAt: "2024-04-18T10:00:00Z",
  },
  {
    id: "19",
    userId: "user10",
    role: "AI Engineer",
    type: "Technical",
    techstack: ["Python", "OpenCV", "YOLO"],
    level: "Mid",
    questions: [
      "How does object detection with YOLO work?",
      "How do you preprocess video data for analysis?",
      "What are challenges with real-time image processing?",
    ],
    finalized: true,
    createdAt: "2024-04-19T10:00:00Z",
  },
  {
    id: "20",
    userId: "user10",
    role: "Data Engineer",
    type: "Technical",
    techstack: ["Apache Spark", "Airflow", "BigQuery"],
    level: "Senior",
    questions: [
      "How do you build a data pipeline using Airflow?",
      "What are transformations in Spark?",
      "How do you handle large-scale ETL processes?",
    ],
    finalized: true,
    createdAt: "2024-04-20T10:00:00Z",
  },
  {
    id: "21",
    userId: "user11",
    role: "Business Analyst",
    type: "Behavioral",
    techstack: ["Excel", "Power BI", "SQL"],
    level: "Mid",
    questions: [
      "How do you gather business requirements?",
      "Describe your experience with data visualization tools.",
      "How do you manage stakeholder communication?",
    ],
    finalized: true,
    createdAt: "2024-04-21T10:00:00Z",
  },
  {
    id: "22",
    userId: "user12",
    role: "Automation Engineer",
    type: "Technical",
    techstack: ["Python", "Selenium", "Jenkins"],
    level: "Junior",
    questions: [
      "How do you set up automation scripts using Selenium?",
      "What is the role of Jenkins in CI?",
      "How do you handle flaky test cases?",
    ],
    finalized: true,
    createdAt: "2024-04-22T10:00:00Z",
  },
  {
    id: "23",
    userId: "user12",
    role: "Site Reliability Engineer",
    type: "Technical",
    techstack: ["Prometheus", "Grafana", "Kubernetes"],
    level: "Mid",
    questions: [
      "What is observability in SRE?",
      "How do you implement alerting with Prometheus?",
      "What are error budgets?",
    ],
    finalized: true,
    createdAt: "2024-04-23T10:00:00Z",
  },
  {
    id: "24",
    userId: "user13",
    role: "Web Developer",
    type: "Technical",
    techstack: ["HTML", "CSS", "JavaScript", "Bootstrap"],
    level: "Junior",
    questions: [
      "How do you make a website responsive?",
      "What is the box model in CSS?",
      "How do you optimize images for the web?",
    ],
    finalized: true,
    createdAt: "2024-04-24T10:00:00Z",
  },
  {
    id: "25",
    userId: "user14",
    role: "AI Product Manager",
    type: "Behavioral",
    techstack: ["ChatGPT", "Figma", "Agile"],
    level: "Senior",
    questions: [
      "How do you plan an AI feature?",
      "What are ethical concerns in AI product development?",
      "How do you manage the lifecycle of an AI product?",
    ],
    finalized: true,
    createdAt: "2024-04-25T10:00:00Z",
  },
  {
    id: "26",
    userId: "user15",
    role: "Embedded Systems Engineer",
    type: "Technical",
    techstack: ["C", "Arduino", "RTOS"],
    level: "Mid",
    questions: [
      "What is the role of RTOS in embedded systems?",
      "How do you handle interrupts?",
      "Explain communication between microcontrollers.",
    ],
    finalized: true,
    createdAt: "2024-04-26T10:00:00Z",
  },
  {
    id: "27",
    userId: "user16",
    role: "Robotics Engineer",
    type: "Technical",
    techstack: ["ROS", "Python", "Gazebo"],
    level: "Senior",
    questions: [
      "How do you simulate a robot in Gazebo?",
      "What is SLAM and how is it implemented?",
      "How do robots navigate autonomously?",
    ],
    finalized: true,
    createdAt: "2024-04-27T10:00:00Z",
  },
  {
    id: "28",
    userId: "user17",
    role: "SEO Specialist",
    type: "Behavioral",
    techstack: ["Google Analytics", "Ahrefs", "WordPress"],
    level: "Junior",
    questions: [
      "What are on-page SEO strategies?",
      "How do you track keyword performance?",
      "What is link building and why is it important?",
    ],
    finalized: true,
    createdAt: "2024-04-28T10:00:00Z",
  },
  {
    id: "29",
    userId: "user18",
    role: "Technical Program Manager",
    type: "Mixed",
    techstack: ["Jira", "Confluence", "Slack"],
    level: "Mid",
    questions: [
      "How do you manage cross-functional teams?",
      "Describe a successful project you led.",
      "How do you handle technical blockers?",
    ],
    finalized: true,
    createdAt: "2024-04-29T10:00:00Z",
  },
  {
    id: "30",
    userId: "user19",
    role: "Support Engineer",
    type: "Behavioral",
    techstack: ["Zendesk", "SQL", "Linux"],
    level: "Junior",
    questions: [
      "How do you handle difficult customer tickets?",
      "What is your process for debugging an issue?",
      "How do you document recurring issues?",
    ],
    finalized: true,
    createdAt: "2024-04-30T10:00:00Z",
  },
  {
    id: "31",
    userId: "user20",
    role: "Computer Vision Engineer",
    type: "Technical",
    techstack: ["OpenCV", "YOLOv8", "ONNX"],
    level: "Senior",
    questions: [
      "How do you convert a model to ONNX?",
      "What are the trade-offs between YOLOv5 and YOLOv8?",
      "How do you evaluate object detection performance?",
    ],
    finalized: true,
    createdAt: "2024-05-01T10:00:00Z",
  },
  {
    id: "32",
    userId: "user21",
    role: "Prompt Engineer",
    type: "Technical",
    techstack: ["LangChain", "OpenAI", "Vector DBs"],
    level: "Mid",
    questions: [
      "How do you chain LLM prompts effectively?",
      "What are embedding vectors used for?",
      "How do you reduce hallucinations in LLM outputs?",
    ],
    finalized: true,
    createdAt: "2024-05-02T10:00:00Z",
  },
  {
    id: "33",
    userId: "user22",
    role: "Tech Lead",
    type: "Behavioral",
    techstack: ["Agile", "Mentoring", "Design Reviews"],
    level: "Senior",
    questions: [
      "How do you manage code quality across the team?",
      "What’s your strategy for mentoring junior developers?",
      "How do you resolve architecture conflicts?",
    ],
    finalized: true,
    createdAt: "2024-05-03T10:00:00Z",
  },
  {
    id: "34",
    userId: "user23",
    role: "Chatbot Developer",
    type: "Technical",
    techstack: ["Dialogflow", "Rasa", "Node.js"],
    level: "Mid",
    questions: [
      "How do you train custom intents in Dialogflow?",
      "What are fallback intents and how are they used?",
      "Compare Dialogflow and Rasa.",
    ],
    finalized: true,
    createdAt: "2024-05-04T10:00:00Z",
  },
  {
    id: "35",
    userId: "user24",
    role: "Bioinformatics Engineer",
    type: "Technical",
    techstack: ["Python", "Biopython", "R"],
    level: "Mid",
    questions: [
      "How do you analyze genomic data?",
      "What is a FASTA file?",
      "How do you visualize biological networks?",
    ],
    finalized: true,
    createdAt: "2024-05-05T10:00:00Z",
  },
  {
    id: "36",
    userId: "user25",
    role: "VR Developer",
    type: "Technical",
    techstack: ["Unity", "C#", "Oculus SDK"],
    level: "Junior",
    questions: [
      "How do you optimize VR apps for performance?",
      "What are interaction models in VR?",
      "Explain 6DOF in VR tracking.",
    ],
    finalized: true,
    createdAt: "2024-05-06T10:00:00Z",
  },
  {
    id: "37",
    userId: "user26",
    role: "Data Privacy Officer",
    type: "Behavioral",
    techstack: ["GDPR", "Compliance", "Risk Assessment"],
    level: "Senior",
    questions: [
      "What is the difference between anonymization and pseudonymization?",
      "How do you ensure data subject rights are protected?",
      "What are key elements of a privacy impact assessment?",
    ],
    finalized: true,
    createdAt: "2024-05-07T10:00:00Z",
  },
  {
    id: "38",
    userId: "user27",
    role: "Hardware Engineer",
    type: "Technical",
    techstack: ["Verilog", "VHDL", "FPGA"],
    level: "Mid",
    questions: [
      "Compare Verilog and VHDL.",
      "How do you debug an FPGA implementation?",
      "Explain the process of hardware synthesis.",
    ],
    finalized: true,
    createdAt: "2024-05-08T10:00:00Z",
  },
  {
    id: "39",
    userId: "user28",
    role: "IoT Developer",
    type: "Technical",
    techstack: ["MQTT", "ESP32", "Node-RED"],
    level: "Mid",
    questions: [
      "How does MQTT differ from HTTP?",
      "How do you collect sensor data from ESP32?",
      "What is edge computing in IoT?",
    ],
    finalized: true,
    createdAt: "2024-05-09T10:00:00Z",
  },
  {
    id: "40",
    userId: "user29",
    role: "Game Designer",
    type: "Behavioral",
    techstack: ["Unity", "Trello", "Sketch"],
    level: "Junior",
    questions: [
      "How do you design game mechanics?",
      "What makes a game addictive?",
      "How do you balance difficulty levels?",
    ],
    finalized: true,
    createdAt: "2024-05-10T10:00:00Z",
  },
];
